version: '3'

services:
  dashboard:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dashboard
    container_name: dashboard
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./:/var/www
